apiVersion: v3
name: elemental-operator
description: Rancher Elemental Operator
version: 0.0.0
appVersion: 0.0.0
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/namespace: cattle-elemental-system
  catalog.cattle.io/release-name: elemental-operator
  catalog.cattle.io/provides-gvr: elemental.cattle.io/v1beta1
  catalog.cattle.io/os: linux
