area/register:
- changed-files:
  - any-glob-to-any-file:
    - 'cmd/register/*'
    - 'pkg/config/*'
    - 'pkg/tpm/*'
    - 'pkg/dmidecode/*'

area/tests:
- changed-files:
  - any-glob-to-any-file:
    - 'tests/*'
    - 'tests/**'
    - '*/**/*_test.go'

area/operator:
- changed-files:
  - any-glob-to-any-file:
    - 'pkg/**/*'
    - 'cmd/operator/*'

area/build:
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - '.golangci.yaml'
    - '.goreleaser.yaml'
    - 'Dockerfile'
    - 'Makefile'
    - 'go.mod'
    - 'go.sum'

area/docs:
- changed-files:
  - any-glob-to-any-file:
    - 'Examples/**/*'

area/chart:
- changed-files:
  - any-glob-to-any-file:
    - 'chart/**/*'

