project_name: elemental-operator
builds:
  - main: ./cmd/operator
    binary: elemental-operator
    id: elemental-operator
    ldflags:
      - -w -s
      - -X github.com/rancher/elemental-operator/version.Version={{.Tag}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - main: ./cmd/installer
    binary: elemental-installer
    id: elemental-installer
    ldflags:
      - -w -s
      - -X github.com/rancher/elemental-operator/version.Version={{.Tag}}
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
archives:
  # Default template uses underscores instead of -
  - name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
