{{ $defChannelName := "" }}
{{ $defChannels := .Values.defaultChannels }}

{{ if and .Values.channel .Values.channel.image .Values.channel.tag .Values.channel.name }}
{{ $defChannelName := .Values.channel.name }}
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: {{ .Values.channel.name }}
  namespace: fleet-default
spec:
  options:
    image: {{ .Values.channel.image }}:{{ .Values.channel.tag }}
  type: custom
{{ end }}

{{ $includedChannels := dict }}
{{ range $key, $channel := $defChannels }}
  {{ if $channel.included }}
    {{ $_ := set $includedChannels $channel.name $channel }}
  {{ end }}
{{ end }}

{{ range $_, $channel := $defChannels }}
---
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: {{ $channel.name }}
  namespace: fleet-default
spec:
  deleteNoLongerInSyncVersions: {{ $channel.deleteNoLongerInSyncVersions }}
  enabled: {{ $channel.enabled }}
  options:
    image: {{ $channel.image }}
  type: custom
{{ end }}

{{ range $_, $channel := (lookup "elemental.cattle.io/v1beta1" "ManagedOSVersionChannel" "fleet-default" "").items }}
  {{ if and (eq (index $channel.metadata.labels "app.kubernetes.io/managed-by") "Helm") (not (hasKey $includedChannels $channel.metadata.name)) }}
    {{ if and (ne $channel.metadata.name "unstable-testing-channel") (ne $channel.metadata.name $defChannelName) }}
---
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: {{ $channel.metadata.name }}
  namespace: fleet-default
spec:
    {{- toYaml $channel.spec | nindent 2}}
    {{ end }}
  {{  end }}
{{ end }}
