kind: APIService
apiVersion: management.cattle.io/v3
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}
  secretNamespace: {{ .Release.Namespace }}
  pathPrefixes:
  - /elemental/
