{{ if and .Values.channel .Values.channel.repository .Values.channel.tag }}
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-teal-channel
  namespace: fleet-default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-failed
spec:
  options:
    image: {{ .Values.channel.repository }}:{{ .Values.channel.tag }}
  type: custom
{{ end }}
