apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups:
    - management.cattle.io
  resources:
    - 'settings'
  verbs:
    - 'get'
    - 'watch'
    - 'list'
- apiGroups:
  - ""
  resources:
  - 'events'
  verbs:
  - 'patch'
  - 'create'
- apiGroups:
  - ""
  resources:
  - 'secrets'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
  - 'create'
  - 'update'
  - 'patch'
  - 'delete'
- apiGroups:
  - ""
  resources:
  - 'pods'
  - 'serviceaccounts'
  verbs:
  - 'get'
  - 'create'
  - 'delete'
  - 'list'
  - 'watch'
- apiGroups:
    - "rbac.authorization.k8s.io"
  resources:
    - 'rolebindings'
    - 'roles'
  verbs:
    - 'get'
    - 'create'
    - 'delete'
    - 'watch'
- apiGroups:
  - ""
  resources:
  - 'pods/log'
  verbs:
  - 'get'
- apiGroups:
  - elemental.cattle.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - fleet.cattle.io
  resources:
  - 'bundles'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - 'list'
  - 'get'
- apiGroups:
    - cluster.x-k8s.io
  resources:
    - machines
  verbs:
    - 'list'
    - 'get'
    - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{.Release.Namespace}}
