# SPDX-License-Identifier: Apache-2.0
#!BuildTag: rancher/elemental-operator-crds:latest
#!BuildTag: rancher/elemental-operator-crds:%VERSION%
#!BuildTag: rancher/elemental-operator-crds:%VERSION%-%RELEASE%
apiVersion: v2
name: elemental-operator-crds
description: A Helm chart for deploying Rancher Elemental Operator CRDs
version: "%VERSION%"
appVersion: "%VERSION%"
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-elemental-system
  catalog.cattle.io/release-name: elemental-operator-crds
  catalog.cattle.io/hidden: true # Hide specific charts. Only use on CRD charts.
