apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        image: {{ template "registry_url" . }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        args:
        - cleanup
      serviceAccountName: {{ .Release.Name }}
      restartPolicy: Never
