{{ if and .Values.channel .Values.channel.repository .Values.channel.tag }}
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-teal-channel
  namespace: fleet-default
spec:
  options:
    image: {{ template "system_default_registry" . }}{{ .Values.channel.repository }}:{{ .Values.channel.tag }}
  type: custom
{{ end }}
