apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: test-machine
spec:
  config:
    data:
      write_files:
        content: V2h5IGFyZSB5b3UgY2hlY2tpbmcgdGhpcz8K
        encoding: b64
    elemental:
      install:
        device: /dev/vda
        iso: https://something.example.com
