apiVersion: v2
name: elemental-operator-defaults
description: A Helm chart for deploying Rancher Elemental Operator default resources
version: 0.0.0
appVersion: 0.0.0
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: Elemental Operator default resources
  catalog.cattle.io/experimental: "true"
  catalog.cattle.io/namespace: cattle-elemental-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: elemental-operator-defaults
  catalog.cattle.io/hidden: "true"
