{{ if and .Values.channel .Values.channel.image .Values.channel.tag .Values.channel.name }}
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: {{ .Values.channel.name }}
  namespace: fleet-default
spec:
  options:
    image: {{ .Values.channel.image }}:{{ .Values.channel.tag }}
  type: custom
{{ end }}
