apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-helm-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-helm-hook
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cattle-globalrole-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}-helm-hook
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-helm-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-helm-hook
    spec:
      serviceAccountName: {{ .Release.Name }}-helm-hook
      containers:
      - name: crd-keep-policy
        image: rancher/kubectl:v1.24.13
        command:
          - "kubectl"
          - "annotate"
          - "crds"
          - "--selector=release-name={{ .Values.legacyReleaseName }}"
          - "helm.sh/resource-policy=keep"
          - "--overwrite=true"
      - name: crd-release-name
        image: rancher/kubectl:v1.24.13
        command:
          - "kubectl"
          - "annotate"
          - "crds"
          - "--selector=release-name={{ .Values.legacyReleaseName }}"
          - "meta.helm.sh/release-name={{ .Values.newCRDsReleaseName }}"
          - "--overwrite=true"
      restartPolicy: Never
  backoffLimit: 2
