name: Build and publish development charts
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  dev-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and publish OBS dev charts
        uses: "./.github/actions/chart"
        with:
          build_env: dev
